### ISSUE TITLE
[Bug Report]Zorin Apperance

### ISSUE THREAD

**Issue by Boffice** [ZorinOS/zorin-desktop-themes#15] opened 2021-12-04 16:48 UTC
Hello,

I had some issue with my OS, more details can be found bellow:
https://forum.zorin.com/t/sos-critical-issue-stuck-in-cli-mode/12360/22

**TL;DR:** 
I was stuck in CLI mode and had to use ```sudo apt install --reinstall zorin-os-desktop``` to fix it, accordingly lost access to PRO functions in Zorin Appearance. 

Is there a way to restore PRO?

**Comment by ArtyomZorin** [comment] 2021-12-11 16:53
If you're missing the additional desktop layouts in Zorin Appearance while running Zorin OS Pro, please open the Terminal (Ctrl+Alt+T) and enter this command to re-install them: `sudo apt install zorin-appearance-layouts-shell-premium zorin-os-pro`

Closing as this is a support request and not a bug report.

**Closed by ArtyomZorin** 2021-12-11 16:53 UTC
